name: protection
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  flutter_acrylic: ^1.1.4
  fluent_ui: ^4.11.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  iconsax_flutter: ^1.0.0
  gap: ^03.0.1
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  objectbox_generator: ^4.1.0




flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
