name: Build Flutter Linux Release

on:
  push:
    tags:
      - "v*" # Trigger only when pushing a tag starting with "v"

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.x" # Specify your desired Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Build Linux release
        run: |
          flutter build linux --release

      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: build/linux/x64/release/bundle
