name: Flutter Desktop CI/CD

on:
  push:
    tags:
      - "v*" # Triggers on tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.5"
          channel: "stable"

      - name: Enable Desktop Support
        run: flutter config --enable-linux-desktop --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release

      - name: Build Linux Release
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux --release

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/Release/

      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: build/linux/x64/release/bundle/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            🚀 Release build includes:
            - ✅ Windows (EXE)
            - ✅ Linux (AppImage or bundle)
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Release Files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-release/**
            artifacts/linux-release/**
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
